Imagen de portada de C√≥mo habilitar GitHub Actions en tu perfil README para un gr√°fico de contribuci√≥n de comer serpientes üêç
michelle mannering
michelle mannering
Publicado en28 junio 2021 ‚Ä¢ Actualizado en23 de febrero de 2022

C√≥mo habilitar GitHub Actions en su perfil README para un gr√°fico de contribuci√≥n de comer serpientes üêç
#
github
#
reducci√≥n
#
fuente abierta
#
tutorial
Git Good (serie de 9 partes)
1
Uso de la CLI de GitHub para actualizar su repositorio
2
C√≥mo crear y anclar una esencia en GitHub
...
5 partes m√°s...
8
C√≥mo usar GitHub Pages para alojar su sitio web, incluso con m√∫ltiples repositorios
9
C√≥mo crear un perfil README para su organizaci√≥n
Mucha gente ha estado hablando y compartiendo sus archivos README de perfil de GitHub. Fue un proyecto que lanzamos el a√±o pasado y a los desarrolladores les encanta. A medida que esta funci√≥n se hizo m√°s popular, m√°s desarrolladores crearon plantillas, complementos y aplicaciones para que los use en su perfil.

Esta publicaci√≥n de Supritha me llam√≥ la atenci√≥n. Me gusta la forma en que hablan sobre varios fragmentos de c√≥digo para tener en su L√âAME de su perfil de GitHub.

suprita 
¬øC√≥mo tener un perfil incre√≠ble de GitHub?
Supritha Ravishankar „Éª 8 de junio de 21 „Éª 5 minutos de lectura
#github #markdown #c√≥digo abierto #git
Uno de los comentarios de Guillaume Falourd apuntaba a un proyecto realmente genial de Platane .

Logotipo de GitHub Platano / hundido
üü©‚¨ú Genera un juego de serpientes a partir de un gr√°fico de contribuciones de usuarios de github y genera una captura de pantalla como svg o gif animado
hundirse
Mercado GitHub definiciones de tipo estilo de c√≥digo

Genera un juego de serpientes a partir de un gr√°fico de contribuciones de usuarios de github



Extraiga el gr√°fico de contribuci√≥n de un usuario de github. Convi√©rtalo en un juego de serpientes, genere un camino de serpiente donde las c√©lulas se comen de manera ordenada.

Genera una imagen gif o svg .

Disponible como acci√≥n de github. Genera autom√°ticamente una nueva imagen al final del d√≠a. Lo que lo convierte en un excelente L√©ame del perfil de github

Uso
acci√≥n de github

- usa : Platane/snk@master 
  con :
     # nombre de usuario de github para leer el gr√°fico de contribuci√≥n de (**requerido**) 
    # usando contexto de acci√≥n var `github.repository_owner` o usuario especificado 
    github_user_name : ${{ github.repository_owner }}

    # ruta del archivo gif generado 
    # Si se deja vac√≠o, el archivo gif no se generar√° 
    gif_out_path : dist/github-snake.gif

    # ruta del archivo svg generado 
    # Si se deja vac√≠o, el archivo svg no se generar√° 
    svg_out_path : dist/github-snake.svg
ejemplo con trabajo cron

demostraci√≥n interactiva


platane.github.io/snk

local

npm install
npm
‚Ä¶
Ver en GitHub
Utiliza GitHub Actions para crear y actualizar el gr√°fico de contribuci√≥n de un usuario y luego hace que una serpiente se coma todas sus contribuciones. La salida genera un archivo gif, que luego puede mostrar en su perfil de GitHub README. Pens√© que esto era genial, as√≠ que comenc√© a agregarlo a mi perfil.

Paso 1. Configurar acciones de GitHub
Lo primero que debe asegurarse antes de comenzar este proyecto es que tiene la configuraci√≥n de GitHub Actions. Dir√≠gete a tu perfil y aseg√∫rate de que la pesta√±a "Acciones" est√© disponible. Todo el mundo deber√≠a tener ahora esta funci√≥n.

Bot√≥n de acciones

Luego, dir√≠gete a Platane's Action (disponible en Marketplace) y haz una copia del c√≥digo. Deber√° agregar este fragmento en su archivo de Acciones.

Paso 2. Creaci√≥n de su archivo yaml GitHub Actions
Esta es definitivamente la parte donde me qued√© atascado. Al mirar el c√≥digo, no estaba seguro de d√≥nde agregar exactamente las l√≠neas de c√≥digo mencionadas en Marketplace .

Despu√©s de ver la forma en que Platane ten√≠a la configuraci√≥n de su archivo de Acciones, pude generar el c√≥digo (con un poco de ayuda de Bdougie , por supuesto).

Agregu√© el fragmento de c√≥digo completo a continuaci√≥n y agregu√© muchos comentarios (espero que sea f√°cil de entender).

Puede copiar este c√≥digo directamente en un archivo *.yml en blanco. Aseg√∫rese de crear un nuevo archivo *.yml en el siguiente directorio:

YOUR_GITHUB_USERNAME --> .github --> flujos de trabajo --> FILE_NAME.yml

# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Paso 3. Ejecutar acciones de GitHub
Una vez que haya agregado el c√≥digo anterior y lo haya confirmado, dir√≠jase a la pesta√±a Acciones. En "Flujos de trabajo", deber√≠a ver la acci√≥n "Generar serpiente" que cre√≥ anteriormente.

flujo de trabajo

Haga clic en "Ejecutar flujo de trabajo" y observe c√≥mo se ejecuta su flujo de trabajo. Incluso puede expandir su flujo de trabajo y ver lo que sucede en tiempo real.


GIF
Ejecutar acciones

Una vez que su flujo de trabajo haya terminado de ejecutarse, deber√≠a haber recibido una marca de verificaci√≥n verde ‚úÖ "construir". Si es as√≠, esto significa que su Acci√≥n est√° funcionando bien. Si no, tendr√°s que revisar el c√≥digo y ver d√≥nde est√°n los errores. El estado de "construcci√≥n" deber√≠a darle alguna indicaci√≥n de d√≥nde se encuentran sus errores. Tambi√©n puede compararlo con el archivo yaml en mi perfil README de GitHub .

construir verde

If you have the green "build" ‚úÖ then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

GIFSalida de c√≥digo

Step 4. Adding a contribution-eating snake to your profile
Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

GIFSerpienteComer
Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?

Git Good (9 Part Series)
1
Using the GitHub CLI to update your repo
2
How to create and pin a gist on GitHub
...
5 more parts...
8
How to use GitHub Pages to host your website, even with multiple repos
9
How to create a Profile README for your Organisation
Top comments (27)

Subscribe
Foto
Agregar a la discusi√≥n
 
 
imagen de perfil de kushaltanna24
KushalTanna24
‚Ä¢
3 jun 22

Work fine.! Here is mine - KushalTanna24


2
 likes
Like
Reply
 
 
msoftware profile image
Michael jentsch
‚Ä¢
9 jul 21

Great tutorial! Works for me.
Here's mine - github.com/msoftware


2
 likes
Like
Reply
 
 
gustavohgmartins profile image
Gustavo Martins
‚Ä¢
2 sept 21

Awsome! How did you change the background-color?


Like
Reply
 
 
mishmanners profile image
Michelle Mannering 
‚Ä¢
2 sept 21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.


1
 like
Like
Thread
 
gustavohgmartins profile image
Gustavo Martins
‚Ä¢
2 sept 21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voil√°


2
 likes
Like
Thread
 
mishmanners profile image
Michelle Mannering 
‚Ä¢
3 sept 21

Awesome! Glad to be of help üòÑ


1
 like
Like
Reply
 
 
bpolaswar profile image
Bhumesh Polaswar
‚Ä¢
17 oct 21

Great worked for me. See github.com/bpolaswar
Thanks.


2
 likes
Like
Reply
 
 
hudsonpufferfish profile image
Hudson Nguyen
‚Ä¢
7 ene

I got error "The process '/usr/bin/git' failed with exit code 128". Even though I tried to generate a new personal access token, it didn't work. Anybody has any solution for this error?


1
 like
Like
Reply
 
 
viveeeeeek profile image
VivekS.
‚Ä¢
2 oct 21

Awesome!


1
 like
Like
Reply
 
 
adityamangal1 profile image
Aditya Mangal
‚Ä¢
22 jul 21

Awesome Tutorial! üêç


1
 like
Like
Reply
 
 
zieldecastro profile image
Josiel de Castro Goudinho
‚Ä¢
14 sept 21 ‚Ä¢ Edited on 14 sept

It does not work for me. Can someone help me?
github.com/zieldecastro
instagram.com/zieldecastro/


1
 like
Like
Reply
 
 
shasank27 profile image
Shasank Periwal
‚Ä¢
7 ago 21 ‚Ä¢ Edited on 7 ago

Great tutorial!
But can anyone help me, its not showing all my contributions
github.com/shasank27/shasank27


1
 like
Like
Reply
 
 
mishmanners profile image
Michelle Mannering 
‚Ä¢
6 sept 21 ‚Ä¢ Edited on 6 sept

Hey Shasank. I can't see it on your profile, but to show all contributions, you need to make sure all contributions are turned on your profile. You can do this in your settings:

github.com/YOUR_PROFILE --> Settings --> Profile

Then scroll down to "Contributions" and check the box that says "Include private contributions on my profile".

Hope that helps.


1
 like
Like
Reply
 
 
phuocantd profile image
An Nguy·ªÖn Ph∆∞·ªõc
‚Ä¢
31 may 22

How to auto build workflow everyday


1
 like
Like
Reply
 
 
wkylin profile image
wkylin.w
‚Ä¢
1 may 22

Here's mine:
github.com/wkylin


1
 like
Like
Reply
 
 
laurasiiia profile image
Laura
‚Ä¢
2 ene 22 ‚Ä¢ Edited on 2 ene

Hi, i did everything right and even got the "build" status. But no output branch was created... why is that? Can someone help me? github.com/laurasiiia


1
 like
Like
Reply
 
 
mishmanners profile image
Michelle Mannering 
‚Ä¢
3 ene 22

I assume you're working off this folder: github.com/laurasiiia/laurasiiia/b...

Since you've got a newer repo (mine account was set up a number of years ago), you have the default branch set to "main". You might need to change the code to be "main" instead of "master".

I created a PR for you: github.com/laurasiiia/laurasiiia/p...
(run it and see if that works)... it might not but worth a shot. Feel free to jump in other people üòÑ


1
 like
Like
Reply
 
 
nirav97120 profile image
Nirav Prajapati
‚Ä¢
16 dic 22

Awesome My github profile


1
 like
Like
Reply
 
 
imagen de perfil de wisnuaero
Adida Wisnu Akbara
‚Ä¢
7 dic 22

here's mine - github.com/wisnuaero


1
 like
Like
Reply
 
 
imagen de perfil de brayheart
Tyler Bray
‚Ä¢
9 nov 22

Thanks for making this guide!


1
 like
Like
Reply
 
 
imagen de perfil de matheusroichman
Matheus Roichman
‚Ä¢
2 nov 22

Mine is not showing all the contributions :(
github.com/MatheusRoichman/Matheus...


1
 like
Like
Reply
View full discussion (27 comments)
Code of Conduct ‚Ä¢ Report abuse
¬°Hola! ¬°Soy No√©!

Hey, my name is Noah and I‚Äôm the one who set up this ad!

My job is to get you to join DEV, so if you fancy doing me a favor, I‚Äôd love for you to create an account.
 
If you found DEV from searching around, here are a couple of our most popular articles on DEV:

9 Projects You Can Do To Become a Frontend Master
101 Tips For Being A Great Programmer
Full Stack Developer‚Äôs Roadmap
Read next
c_yatteau imagen de perfil
4 Trivia APIs üßê (no API Key required!)
Courtney Yatteau - Jan 5

imagen de perfil de leereilly
Your GitHub year in review - 10 fun ways to visualize your contributions
Lee Reilly - Jan 9

nombre en clave una imagen de perfil
Depuraci√≥n de flujos y colecciones
Shai Almog -3 de enero

imagen de perfil de shreyvijayvargiya
Las 5 principales bibliotecas de IU nativas de React
shrey vijayvargiya -4 de enero


michelle mannering
Seguir
Defensor del desarrollador | Reina del hackat√≥n | Ponente internacional
LOCALIZACI√ìN
Australia
EDUCACI√ìN
la universidad de melbourne
TRABAJA
Defensor del desarrollador en GitHub
UNIDO
28 mayo 2020
M√°s de Michelle Mannering
¬øPor qu√© 'lanzar' un proyecto? C√≥mo automatizar lanzamientos
# c√≥digo abierto # productividad # github # herramientas
C√≥mo prepararse para el Hacktoberfest 2022
# hacktoberfest # fuente abierta # tutorial
Funciones sin c√≥digo de GitHub
# github # principiantes # productividad # c√≥digo abierto

# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: LauraVaGarciaA
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
